spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finans
    username: finansuser
    password: User@123
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: admin
logging:
  level:
    root:
    com:
      finapps: INFO